### ISSUE TITLE
No Data For Peppymeter on a pi 5

### ISSUE THREAD

**Issue by martbrad11** [spagoc/PeppyMeter-4-Linux-desktop#1]
I'm using a pi 5 with bookworm. I had already installed peppymeter but could not get it to work. I then read that it doesn't work with pipeline and found your code. I have copied the config.txt and the scripts but I don't see any audio data. The VU meter window starts OK. If I cat the fifo pipe there is nothing there. Also if I use qwnpgraph there is no peppymeter node. What am I doing wrong?

**Comment by spagoc** [comment]
You are on arm architecture so you have to compile the C file. Try:
$ sudo apt install libpipewire-0.3-dev
$ gcc -Wall pwstream4peppymet.c -o pwstream4peppymet $(pkg-config --cflags --libs libpipewire-0.3) -lm

In any case there will be no peppymeter node in qpwgraph, maybe because bookworm has an old pipewire version: 0.3.65

![20240513_19h25m04s_grim](https://github.com/spagoc/PeppyMeter-4-Linux-desktop/assets/1367579/5482529a-c7ef-4af7-bead-b638d4d3c341)

**Comment by martbrad11** [comment]
Thanks for taking the time to help.
I should have realised the original c file wasn't arm. I'll try your suggestion tomorrow.
Many thanks
Martin

**Comment by martbrad11** [comment]
I compiled as you said and it now works. Thank you
Martin

**Comment by spagoc** [comment]
You're welcome

**Comment by spagoc** [comment]
You're welcome
